### PR TITLE
home page

### PR DESCRIPTION
**Pull request by jeffhcs**
Added dummy database and home page with signin/signout.

### CODE REVIEW

**Review by seajunk — DISMISSED** [review]

**Review by seajunk — APPROVED** [review]

**Review by oshley213 — COMMENTED** [review]
good

**Review by oshley213 — COMMENTED** [review]
good

**Review by cymnyon — APPROVED** [review]
goood

**Review by oshley213 — APPROVED** [review]

**Review by seajunk — APPROVED** [review]
Looks good to me!

**Pull request merged**
